### ISSUE TITLE
Exceptions not catched in 0.9.0...(bis)

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#103]
When no peers are availables : 

* Members disappears from members list.
* Pending transactions disappears

And  this exception is not catched : 

>
    Traceback (most recent call last):
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/models/members.py", line 83, in rowCount
        return len(self.pubkeys)
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/models/members.py", line 80, in pubkeys
        return self.community.members_pubkeys()
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/community.py", line 362, in members_pubkeys
        memberships = self.request(bma.wot.Members)
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/community.py", line 381, in request
        return self._cache.request(request, req_args, get_args)
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/community.py", line 87, in request
    cached=False)
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/community.py", line 404, in request
        raise NoPeerAvailable(self.currency, len(nodes))
    cutecoin.tools.exceptions.NoPeerAvailable: Error : No peer answered in meta_brouzouf community (0 peers available)

**Comment by vtexier** [comment]
More infos : 
Peers were not offline, but cutecoin crashed repeatedly trying to reconnect, after loosing peers...
Restarted cutecoin and peers came back, and transactions and all members...

We need to do stress tests on this part of code.

**Comment by Insoleet** [comment]
Should be fixed with latest patch. Could you do some stress test to confirm ?

**Comment by Insoleet** [comment]
The situation should be better now.
https://github.com/ucoin-io/cutecoin/commit/683c8af32fa9f9720ff14b259e85a6522dac282b
