### ISSUE TITLE
Stuck on launching: cutecoin fails while scanning the network

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#112]
Trying to launch Cutecoin, it is being stuck with following error stacktrace:

```
DEBUG:__init__:Error : node uid not found : 
DEBUG:__init__:[[<ucoinpy.documents.peer.BMAEndpoint object at 0x7efd20030080>], [<ucoinpy.documents.peer.BMAEndpoint object at 0x7efd200237b8>], [<ucoinpy.documents.peer.BMAEndpoint object at 0x7efd200238d0>]]
DEBUG:__init__:['HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk', '7p3X4Y7g4PSo9EKd8rqcc4ty7cheQfqyFmVYLAzkHLNu']
DEBUG:__init__:Traversing : next to read : cUzBEnt4LAY3VXYp2mZH2szgC46Q6HMQvqjKr15mqUZ : True
Traceback (most recent call last):
  File "/home/inso/cutecoin/src/cutecoin/gui/mainwindow.py", line 48, in load
  File "/home/inso/cutecoin/src/cutecoin/core/app.py", line 62, in get_account
  File "/home/inso/cutecoin/src/cutecoin/core/app.py", line 162, in load_account
  File "/home/inso/cutecoin/src/cutecoin/core/app.py", line 184, in load_cache
  File "/home/inso/cutecoin/src/cutecoin/core/community.py", line 158, in load_merge_network
  File "/home/inso/cutecoin/src/cutecoin/core/net/network.py", line 71, in merge_with_json
  File "/home/inso/cutecoin/src/cutecoin/core/net/network.py", line 174, in crawling
  File "/home/inso/cutecoin/src/cutecoin/core/net/node.py", line 273, in peering_traversal
  File "/home/inso/cutecoin/src/cutecoin/core/net/node.py", line 271, in peering_traversal
TypeError: 'bool' object is not callable
QThread: Destroyed while thread is still running
```

It would be nice if Cutecoin just skip if an exception is raised, because here I cannot even access my account whereas at least 2 nodes are able to answer requests.

**Comment by Insoleet** [comment]
Fixed in 0.9.1
