### ISSUE TITLE
Cutecoin 0.10.0 Xubuntu 64 bits

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#147]
When launching new version 0.10.0 with Ubuntu 64 bits XFCE desktop I have : 

$ ./cutecoin
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.3-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "src/cutecoin/main.py", line 12, in <module>
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2214, in _find_and_load
    return _find_and_load_unlocked(name, import_)
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2189, in _find_and_load_unlocked
    _call_with_frames_removed(import_, parent)
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
    return f(*args, **kwds)
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2214, in _find_and_load
    return _find_and_load_unlocked(name, import_)
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2203, in _find_and_load_unlocked
    module = _SpecMethods(spec)._load_unlocked()
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
    return self._load_backward_compatible()
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
    spec.loader.load_module(spec.name)
  File "/home/gael/cutecoin/src/cutecoin/gui/__init__.py", line 6, in <module>
ImportError: cannot import name 'QtSvg'

**Comment by Insoleet** [comment]
My bad, build has been fixed. Can you try and confirm please ?

**Comment by galuel** [comment]
Another error ! :)

$ ./cutecoin
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.3-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "src/cutecoin/main.py", line 13, in <module>
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2214, in _find_and_load
    return _find_and_load_unlocked(name, import_)
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2203, in _find_and_load_unlocked
    module = _SpecMethods(spec)._load_unlocked()
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
    return self._load_backward_compatible()
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
    spec.loader.load_module(spec.name)
  File "/home/gael/cutecoin/src/cutecoin/core/app.py", line 13, in <module>
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2214, in _find_and_load
    return _find_and_load_unlocked(name, import_)
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2201, in _find_and_load_unlocked
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'i18n_rc'

**Comment by Insoleet** [comment]
My bad :)

This should be fixed now !

**Comment by galuel** [comment]
Yes it is all ok now ! Note : under XFCE I had to remove appmenu-qt5 :

sudo apt-get remove appmenu-qt5

in order to see the menu in cutecoin.
