### ISSUE TITLE
Division by zero issue on dev branch

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#164]
```bash
/home/moul/Documents/cutecoin/build/res/i18n/langs-1435860778.qrc >> /home/moul/Documents/cutecoin/build/src/i18n_rc.py
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/informations_tab.py", line 96, in refresh
    self.community.computed_dividend
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/community.py", line 152, in computed_dividend
    self.parameters['c'] * block['monetaryMass'] / block['membersCount']
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/informations_tab.py", line 96, in refresh
    self.community.computed_dividend
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/community.py", line 152, in computed_dividend
    self.parameters['c'] * block['monetaryMass'] / block['membersCount']
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/informations_tab.py", line 96, in refresh
    self.community.computed_dividend
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/community.py", line 152, in computed_dividend
    self.parameters['c'] * block['monetaryMass'] / block['membersCount']
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/informations_tab.py", line 96, in refresh
    self.community.computed_dividend
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/community.py", line 152, in computed_dividend
    self.parameters['c'] * block['monetaryMass'] / block['membersCount']
ZeroDivisionError: float division by zero
```

**Comment by Insoleet** [comment]
Are you sure you are up to date ? 

On dev branch, division by zero are already handled : https://github.com/ucoin-io/cutecoin/blob/dev/src/cutecoin/core/community.py

**Comment by M5oul** [comment]
I have deleted the repo, cloned it again, git checkout dev. The interface seems better. But, I still have division by zero in the terminal.

**Comment by Insoleet** [comment]
It's when you run main, or when you build cutecoin ?

**Comment by M5oul** [comment]
When I run the main file.
