### ISSUE TITLE
Can not run dev branch

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#182]
Since https://github.com/ucoin-io/cutecoin/commit/8a8a3dd6b7753681336650a62e012b765654a985, https://github.com/ucoin-io/cutecoin/commit/a8e130afdb4a1070d82f47e26990d34f41bd8753 or https://github.com/ucoin-io/cutecoin/commit/f88e4b8320c34894aa6b1c05a9509f62ba29b704, I can not run dev branch.
Logs:
```bash
Debug enabled : False
Traceback (most recent call last):
  File "src/cutecoin/main.py", line 26, in <module>
    app = Application.startup(sys.argv, cutecoin, loop)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/app.py", line 67, in startup
    app.load()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/app.py", line 181, in load
    self.load_registries()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/app.py", line 201, in load_registries
    data = json.load(identities_data)
  File "/usr/lib64/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 4 column 33 (char 62)
```

**Comment by Insoleet** [comment]
Please remove the file __identities__ in .config/cutecoin.

**Comment by M5oul** [comment]
Thanks, it works.
