### ISSUE TITLE
New issues

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#194]
With latest commits, I encounter new issues:
* Many errors:
```bash
/home/moul/Documents/cutecoin/build/res/i18n/langs-1440271369.qrc >> /home/moul/Documents/cutecoin/build/src/i18n_rc.py
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 136, in handle_identity_change
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 132, in refresh
    self.draw_graph(self._current_identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 106, in draw_graph
    graph.add_certifier_list(certifier_list, identity, identity_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/graph.py", line 187, in add_certifier_list
    arc['max_validation'] = self.community.network.fork_window(self.community.members_pubkeys())
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/network.py", line 186, in fork_window
    return statistics.median([n.fork_window for n in self.nodes if n.software != ""
  File "/usr/lib64/python3.4/statistics.py", line 313, in median
    raise StatisticsError("no median for empty data")
statistics.StatisticsError: no median for empty data
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 136, in handle_identity_change
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 132, in refresh
    self.draw_graph(self._current_identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 106, in draw_graph
    graph.add_certifier_list(certifier_list, identity, identity_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/graph.py", line 187, in add_certifier_list
    arc['max_validation'] = self.community.network.fork_window(self.community.members_pubkeys())
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/network.py", line 186, in fork_window
    return statistics.median([n.fork_window for n in self.nodes if n.software != ""
  File "/usr/lib64/python3.4/statistics.py", line 313, in median
    raise StatisticsError("no median for empty data")
statistics.StatisticsError: no median for empty data
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 136, in handle_identity_change
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 132, in refresh
    self.draw_graph(self._current_identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 106, in draw_graph
    graph.add_certifier_list(certifier_list, identity, identity_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/graph.py", line 187, in add_certifier_list
    arc['max_validation'] = self.community.network.fork_window(self.community.members_pubkeys())
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/network.py", line 186, in fork_window
    return statistics.median([n.fork_window for n in self.nodes if n.software != ""
  File "/usr/lib64/python3.4/statistics.py", line 313, in median
    raise StatisticsError("no median for empty data")
statistics.StatisticsError: no median for empty data
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 136, in handle_identity_change
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 132, in refresh
    self.draw_graph(self._current_identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 106, in draw_graph
    graph.add_certifier_list(certifier_list, identity, identity_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/graph.py", line 187, in add_certifier_list
    arc['max_validation'] = self.community.network.fork_window(self.community.members_pubkeys())
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/network.py", line 186, in fork_window
    return statistics.median([n.fork_window for n in self.nodes if n.software != ""
  File "/usr/lib64/python3.4/statistics.py", line 313, in median
    raise StatisticsError("no median for empty data")
statistics.StatisticsError: no median for empty data
```
* And the charging bar stay stuck at 52% and I can't see transactions:
![52](https://cloud.githubusercontent.com/assets/4758871/9425574/61de03cc-4915-11e5-86bf-55dcb9d1765c.png)

**Comment by M5oul** [comment]
Second issue seems ok right now.

**Comment by Insoleet** [comment]
Nice catch... Should be fixed with latest commit.

**Comment by M5oul** [comment]
Seems to be the same and my WoT graph is empty:
```bash
/home/moul/Documents/cutecoin/build/res/i18n/langs-1440273579.qrc >> /home/moul/Documents/cutecoin/build/src/i18n_rc.py
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 136, in handle_identity_change
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 132, in refresh
    self.draw_graph(self._current_identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 106, in draw_graph
    graph.add_certifier_list(certifier_list, identity, identity_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/graph.py", line 196, in add_certifier_list
    validation = current_validations / max_validation * 100
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 136, in handle_identity_change
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 132, in refresh
    self.draw_graph(self._current_identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 106, in draw_graph
    graph.add_certifier_list(certifier_list, identity, identity_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/graph.py", line 196, in add_certifier_list
    validation = current_validations / max_validation * 100
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 136, in handle_identity_change
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 132, in refresh
    self.draw_graph(self._current_identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 106, in draw_graph
    graph.add_certifier_list(certifier_list, identity, identity_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/graph.py", line 196, in add_certifier_list
    validation = current_validations / max_validation * 100
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 136, in handle_identity_change
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 132, in refresh
    self.draw_graph(self._current_identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 106, in draw_graph
    graph.add_certifier_list(certifier_list, identity, identity_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/graph.py", line 196, in add_certifier_list
    validation = current_validations / max_validation * 100
ZeroDivisionError: division by zero
```

**Comment by M5oul** [comment]
Nice, I do not get those errors. But I get strange thing in WoT graph:
![capture d ecran de 2015-08-22 22-25-09](https://cloud.githubusercontent.com/assets/4758871/9425754/e4a0e782-491c-11e5-8c29-57d04f93cedd.png)

**Comment by Insoleet** [comment]
Yes should be better now. If you want to try out the fork window, you can insert the line 
```python
        return 500
```
Before line 186 of the file src/cutecoin/core/net/api/network.py
This will simulate a forking window of 500 blocks in the network.

**Comment by M5oul** [comment]
Yep, great now.

I have tested forking window. I can see transactions not validated :smile: 

I think this issue can be closed.
