### ISSUE TITLE
New UI proposal

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/cutecoin#196]
Since a lot of things changed since the first version of cutecoin, a new UI should be thought after all we found.

Here are images i'd like to share as proposal for next UI in next version : 

I think we should stop having tabs for each communities. Instead, I suggest a homescreen like this one : 
![beta_mainwindow](https://cloud.githubusercontent.com/assets/1170293/9487341/eb189cde-4bd0-11e5-95fd-3cf9db975522.png)

Then, when we access the "Details" of a Community, we could get the following view : 
![beta_currency_view](https://cloud.githubusercontent.com/assets/1170293/9487451/0a01c278-4bd2-11e5-874e-08ae3116dc40.png)

The tabs would be : 
Wallets : Merge between the Transactions tab and the Wallet tab
Web of Trust : The current WoT tab with the label "You are certified by ..." in the current wallet tab at the top of the new Web of Trust tab.
Search Identities : The current Identities tab
Network : Same as current network tab

The informatons tab could be accessed, maybe, by a click on a "?" link on the homescreen for each communities.

What do you think ?

**Comment by vtexier** [comment]
Very good idea !

Just a few comments... 

On the first screen :
I would rather get rid of the details button, and put instead an highlight when hovering over the community frame, and just click on it to access it.

We need to see the "membership demand expiration date" here, without having to enter the community.

On the second screen : 
You can add a button with the "i" information symbol at the right of "renew membership", to access information window.

**Comment by Insoleet** [comment]
Indeed, clicking on the tile seems more natural for the user. And I agree that we should display here the informations about membership expiration.

The "i" information symbol seems good too. 
I think we can go for it on version 0.11. It should be also a good time to rename cutecoin to a better name, since the UI will change it should not disturb users too much :)

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/bc20b773150c8d2128de5537aef25f10d5d827fe

Check it out ! :)

**Comment by M5oul** [comment]
Feed backs about that new UI refactoring:
* Information tab has disappear?
* [Can't display many accounts in differents tiles](https://github.com/ucoin-io/cutecoin/issues/201)
* I can't open `MB` community tile. It crash, and I get those errors logs:
```bash
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 247, in change_community
    self.community_view.change_community(community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/community_view.py", line 81, in change_community
    self.tab_history.change_community(community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 43, in change_community
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 79, in refresh
    self.refresh_balance()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 138, in refresh_balance
    amount = self.account.amount(self.community)
AttributeError: 'TransactionsTabWidget' object has no attribute 'account'
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 268, in dates_changed
    self.refresh_balance()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 138, in refresh_balance
    amount = self.account.amount(self.community)
AttributeError: 'TransactionsTabWidget' object has no attribute 'account'
./dev.sh : ligne 10 :  4259 Abandon                 (core dumped)python3 src/cutecoin/main.py
```
and it happen sometime opening `Fair_money`` community tile:
```bash
/home/moul/Documents/cutecoin/build/res/i18n/langs-1441319652.qrc >> /home/moul/Documents/cutecoin/build/src/i18n_rc.py
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 247, in change_community
    self.community_view.change_community(community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/community_view.py", line 81, in change_community
    self.tab_history.change_community(community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 43, in change_community
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 79, in refresh
    self.refresh_balance()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 138, in refresh_balance
    amount = self.account.amount(self.community)
AttributeError: 'TransactionsTabWidget' object has no attribute 'account'
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 247, in change_community
    self.community_view.change_community(community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/community_view.py", line 81, in change_community
    self.tab_history.change_community(community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 43, in change_community
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 79, in refresh
    self.refresh_balance()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 138, in refresh_balance
    amount = self.account.amount(self.community)
AttributeError: 'TransactionsTabWidget' object has no attribute 'account'
./dev.sh : ligne 10 :  4083 Abandon                 (core dumped)python3 src/cutecoin/main.py
```

**Comment by Insoleet** [comment]
I forgot some SVGs in the commits. And the bug should be fixed. :)

**Comment by M5oul** [comment]
* Information tab has disappear? I think we should keep it among other tabs.
* My balance in transaction tab is not displayed.
* [Can't display many accounts in differents tiles](https://github.com/ucoin-io/cutecoin/issues/201)
* `Certification` and `Renew membership` buttons is not displayed on `Fair_money`:
![buttons_mb](https://cloud.githubusercontent.com/assets/4758871/9682263/3d3e3bdc-5305-11e5-92ee-5bfca4cd60d3.png)
![buttons_fm](https://cloud.githubusercontent.com/assets/4758871/9682264/3d449a68-5305-11e5-87ee-869c73caa668.png)

Great work by the way :smile:

**Comment by M5oul** [comment]
* I also get a crash:
```bash
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 265, in <lambda>
    action.triggered.connect(lambda checked, account_name=account_name: self.action_change_account(account_name))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 141, in action_change_account
    self.app.change_current_account(self.app.get_account(account_name))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/app.py", line 123, in get_account
    self.load_account(name)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/app.py", line 233, in load_account
    with open(account_path, 'r') as json_data:
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/moul/.config/cutecoin/moul/properties'
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/identities.py", line 136, in <lambda>
    refresh_slot = lambda req, identity=identity: self.refresh_identity(req, identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/identities.py", line 152, in refresh_identity
    self.identities_data[index] = self.identity_data(identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/identities.py", line 108, in identity_data
    join_date = identity.get_join_date(self.community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/registry/identity.py", line 128, in get_join_date
    search = community.bma_access.get(self, qtbma.blockchain.Membership, {'search': self.pubkey})
AttributeError: 'NoneType' object has no attribute 'bma_access'
./dev.sh : ligne 10 :  4250 Abandon                 (core dumped)python3 src/cutecoin/main.py
```
* and errors logs without crash:
```bash
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/identities.py", line 136, in <lambda>
    refresh_slot = lambda req, identity=identity: self.refresh_identity(req, identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/identities.py", line 152, in refresh_identity
    self.identities_data[index] = self.identity_data(identity)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/identities.py", line 108, in identity_data
    join_date = identity.get_join_date(self.community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/registry/identity.py", line 128, in get_join_date
    search = community.bma_access.get(self, qtbma.blockchain.Membership, {'search': self.pubkey})
AttributeError: 'NoneType' object has no attribute 'bma_access'
```

**Comment by Insoleet** [comment]
```
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/moul/.config/cutecoin/moul/properties'
```
I think you did something wrong there...

The "Certification"  and "Renew Membership" buttons were removed from 0.11. New behaviour will be the following : 
- When Connecting to a new community, the user will be asked if he want to register or use an already used account
- If he wants to register, Cutecoin will automatically publish the UID and the Membership demand (like on Android)
- If he wants to connect, Cutecoin will check if the pubkey and the UID are found on the network and if they are the same as the uid/salt/password typed by the user to connect

The only button shown will be to renew membership demand if he is or was a member.

**Comment by M5oul** [comment]
Ok.
Finally, I deleted `~/.conf/cutecoin/`. I add an account, then it crashed:
```bash
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 99, in open_add_account_dialog
    self.action_change_account(self.app.current_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 141, in action_change_account
    self.app.change_current_account(self.app.get_account(account_name))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/app.py", line 122, in get_account
    if name in self.accounts.keys():
TypeError: unhashable type: 'Account'
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 99, in open_add_account_dialog
    self.action_change_account(self.app.current_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 141, in action_change_account
    self.app.change_current_account(self.app.get_account(account_name))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/app.py", line 122, in get_account
    if name in self.accounts.keys():
TypeError: unhashable type: 'Account'
./dev.sh : ligne 10 :  5369 Abandon                 (core dumped)python3 src/cutecoin/main.py
```
Finally, after reopening cutecoin, I could open my accounts.

**Comment by M5oul** [comment]
Cutecoin crash too much/oftenly with that new UI.

**Comment by Insoleet** [comment]
Do you have more details on the crashes?

**Comment by M5oul** [comment]
After cleanning `~/.config/cutecoin`, I add my fair_money account. I try to send money with the new button, cutecoin crash:
```bash
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 259, in change_community
    self.community_view.change_community(community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/community_view.py", line 81, in change_community
    self.tab_history.change_community(community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 43, in change_community
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 68, in refresh
    model = HistoryTableModel(self.app, self.community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/txhistory.py", line 184, in __init__
    self.refresh_transfers()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/txhistory.py", line 270, in refresh_transfers
    for transfer in self.transfers:
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/txhistory.py", line 216, in transfers
    return self.account.transfers(self.community) + self.account.dividends(self.community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/account.py", line 253, in dividends
    return self.wallets[0].dividends(community)
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 158, in open_transfer_money_dialog
    self.password_asker)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transfer.py", line 37, in __init__
    self.wallet = self.account.wallets[0]
IndexError: list index out of range
./dev.sh : ligne 10 :  3967 Abandon                 (core dumped)python3 src/cutecoin/main.py
```
Then, I click on home button, it crash again:
```bash
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 79, in <lambda>
    self.community_view.button_home.clicked.connect(lambda: self.change_community(None))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 259, in change_community
    self.community_view.change_community(community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/community_view.py", line 81, in change_community
    self.tab_history.change_community(community)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 44, in change_community
    self.stop_progress([])
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 104, in stop_progress
    self.table_history.model().sourceModel().refresh_transfers()
AttributeError: 'NoneType' object has no attribute 'sourceModel'
./dev.sh : ligne 10 :  4133 Abandon                 (core dumped)python3 src/cutecoin/main.py
```
Then, I add my meta_brouzouf account:
![adding_registering account](https://cloud.githubusercontent.com/assets/4758871/9735574/1c201efe-563c-11e5-8551-68f96173b2ce.png)
`Connect using your account` button does not works. I have tried `Register your account` button which registrerd a new account to metab_brouzouf network. Finally, I could not add a new account and it finally crashed:
```bash
	Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/password_asker.py", line 39, in future_show
    future.set_result(pwd)
  File "/usr/lib64/python3.4/asyncio/futures.py", line 338, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <Future finished result='tototo'>
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/password_asker.py", line 39, in future_show
    future.set_result(pwd)
  File "/usr/lib64/python3.4/asyncio/futures.py", line 338, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <Future finished result='tototo'>
./dev.sh : ligne 10 :  4257 Abandon                 (core dumped)python3 src/cutecoin/main.py
```

There is other crashes…

**Comment by M5oul** [comment]
It's better now. But I still can't add an account. `Connect using your account` button does not works.

**Comment by Insoleet** [comment]
Ok. I'll look into these bugs, but since i'm trying to reproduce them by developing unit tests it could take some time ! I'll let you know when this is fixed.

**Comment by M5oul** [comment]
Crash when sending money from WoT tab:
```bash
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 292, in send_money_to_node
    self.parent.send_money_to_identity(identity)
AttributeError: 'builtin_function_or_method' object has no attribute 'send_money_to_identity'
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 292, in send_money_to_node
    self.parent.send_money_to_identity(identity)
AttributeError: 'builtin_function_or_method' object has no attribute 'send_money_to_identity'
./dev.sh : ligne 10 :  3363 Abandon                 (core dumped)python3 src/cutecoin/main.py
```

**Comment by M5oul** [comment]
After cleaning `~/.config/cutecoin` and setting my cutecoin parameters without accounts added:
```bash
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 318, in changeEvent
    self.refresh()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 221, in refresh
    self.reset()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 211, in reset
    self.account.identity(self.community)
AttributeError: 'NoneType' object has no attribute 'identity'
```
Then, I try to add an account, I thought those buttons does not works, but I need to click on the side. A bit tricky.
![welcome_button](https://cloud.githubusercontent.com/assets/4758871/9788347/60a4fc96-57c9-11e5-9a66-5f168c0612f3.png)

When I add an account, the account is not added to the list of my accounts:
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 100, in open_add_account_dialog
    self.action_change_account(self.app.current_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 142, in action_change_account
    self.app.change_current_account(self.app.get_account(account_name))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/app.py", line 122, in get_account
    if name in self.accounts.keys():
TypeError: unhashable type: 'Account'
```
There is an issue with names accounts:
![wot_name_account](https://cloud.githubusercontent.com/assets/4758871/9788499/8ee0b8ba-57ca-11e5-9f7c-5f095df3b567.png)
My nickname in `meta_brouzouf` is `m4oul`, but, it is displayed the `moul` `fair_money` account name.
