### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#206]
I am not a member, and I don't have the button to certify people.
![non_member_buttons](https://cloud.githubusercontent.com/assets/4758871/9822689/18f80cb8-58c2-11e5-91cf-4cae0cbcdb4d.png)
As you could on top-left corner, there is not the light and block number displayed. It disapears when changing account. Sometime it is displayed blocks from the other account.

**Comment by Insoleet** [comment]
At the moment it's not a bug but a feature, because why would a non-member want to certify people ? I think it just add confusion...

Nice catch for the light on the bottom left. I'll take a look.

**Comment by M5oul** [comment]
Yep, you are right. We can not certify people when not a member. Great choice :smiley:

**Comment by M5oul** [comment]
I wanted to delete one account to try to get two tiles on same screen. I wanted to delete one account. I click on configure. Then it crash:
```bash
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 177, in open_configure_account_dialog
    dialog = ProcessConfigureAccount(self.app, self.app.current_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/process_cfg_account.py", line 158, in __init__
    self.step.display_page()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/process_cfg_account.py", line 53, in display_page
    self.config_dialog.spinbox_wallets.setValue(nb_wallets)
AttributeError: 'ProcessConfigureAccount' object has no attribute 'spinbox_wallets'
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 177, in open_configure_account_dialog
    dialog = ProcessConfigureAccount(self.app, self.app.current_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/process_cfg_account.py", line 158, in __init__
    self.step.display_page()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/process_cfg_account.py", line 53, in display_page
    self.config_dialog.spinbox_wallets.setValue(nb_wallets)
AttributeError: 'ProcessConfigureAccount' object has no attribute 'spinbox_wallets'
./dev.sh : ligne 10 :  2652 Abandon                 (core dumped)python3 src/cutecoin/main.py
```

**Comment by M5oul** [comment]
I have click on home button in WoT tab with nothing in the search field. It crash:
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/tools/decorators.py", line 8, in wrapper
    asyncio.async(asyncio.coroutine(fn)(*args, **kwargs))
TypeError: reset() takes 1 positional argument but 2 were given
```

**Comment by M5oul** [comment]
I change account, it crash:
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/identities.py", line 46, in data
    expiration_data = self.sourceModel().data(expiration_index, Qt.DisplayRole)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/identities.py", line 154, in data
    return self.identities_data[row][col]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/identities.py", line 46, in data
    expiration_data = self.sourceModel().data(expiration_index, Qt.DisplayRole)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/models/identities.py", line 154, in data
    return self.identities_data[row][col]
IndexError: list index out of range
```

**Comment by Insoleet** [comment]
Should be fixed ! :)

**Comment by M5oul** [comment]
I can't add a community with the `add a community` button. I think this button permit have many tiles. Actually, I can't get many tiles.

**Comment by M5oul** [comment]
Errors logs without crash:
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 284, in select_node
    BlockchainState.VALIDATED
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/registry/identities.py", line 131, in from_handled_data
    self._instances[pubkey].inner_data_changed.emit("BlockchainState")
AttributeError: 'Identity' object has no attribute 'inner_data_changed'
```

**Comment by M5oul** [comment]
I have found an UI bug when seletionning `Rel. som 0` referential on transaction tab when changing tab:
![tx_referential_bug](https://cloud.githubusercontent.com/assets/4758871/9861705/3ff49fa6-5b34-11e5-9a53-617c751f6eb7.png)

**Comment by M5oul** [comment]
On tiles interface, the tile is charging indefinitively when set `Rel. Som. 0` and `Quant. Som. 0` referentials.

**Comment by M5oul** [comment]
crash when going to my two accounts:
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/homescreen.py", line 87, in showEvent
    for tile in self.frame_communities:
TypeError: 'FrameCommunities' object is not iterable
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/network.py", line 330, in handle_change
    self.check_nodes_sync()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/network.py", line 202, in check_nodes_sync
    blocks_occurences = Counter(blocks)
  File "/usr/lib64/python3.4/collections/__init__.py", line 465, in __init__
    self.update(iterable, **kwds)
  File "/usr/lib64/python3.4/collections/__init__.py", line 537, in update
    if isinstance(iterable, Mapping):
  File "/usr/lib64/python3.4/abc.py", line 182, in __instancecheck__
    if subclass in cls._abc_cache:
  File "/usr/lib64/python3.4/_weakrefset.py", line 72, in __contains__
    wr = ref(item)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by M5oul** [comment]
I can't add the account `m4oul` from metab_brouzouf. It tells me "Could not find your identity on the network.".

I have try "register your account" button and it crash:
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/password_asker.py", line 39, in future_show
    future.set_result(pwd)
  File "/usr/lib64/python3.4/asyncio/futures.py", line 338, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <Future finished result='password'>
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/password_asker.py", line 39, in future_show
    future.set_result(pwd)
  File "/usr/lib64/python3.4/asyncio/futures.py", line 338, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <Future finished result='password'>
```

**Comment by M5oul** [comment]
After removing all cutecoin cach, I can get transactions. It stay blocked à 2%:
![2 _blockchain_blocked](https://cloud.githubusercontent.com/assets/4758871/9931091/cf8ae85e-5d38-11e5-8897-824be0fd08ee.png)

**Comment by Insoleet** [comment]
Any log available?

**Comment by Insoleet** [comment]
Ok should be fixed.

**Comment by M5oul** [comment]
No logs available. Should be fixed. It stayed stucked again then get fully charged.

**Comment by Insoleet** [comment]
Can you explain what exactly happened by "it get stucked again" ?

**Comment by M5oul** [comment]
I saw the loading bar which stayed stucked at 2% for a while, then all transactions were here.

**Comment by Insoleet** [comment]
Ow... really weird. The bar never filled the 100% ?

**Comment by M5oul** [comment]
It filled 100%.

**Comment by M5oul** [comment]
crash when clicking home button:
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 77, in <lambda>
    self.homescreen.button_disconnect.clicked.connect(lambda :self.action_change_account(""))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 161, in action_change_account
    self.community_view.change_account(self.app.current_account, self.password_asker)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/community_view.py", line 97, in change_account
    self.tab_history.change_account(account, self.password_asker)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 73, in change_account
    self.connect_progress()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 119, in connect_progress
    self.app.current_account.loading_progressed.connect(progressing)
AttributeError: 'NoneType' object has no attribute 'loading_progressed'
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 77, in <lambda>
    self.homescreen.button_disconnect.clicked.connect(lambda :self.action_change_account(""))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 161, in action_change_account
    self.community_view.change_account(self.app.current_account, self.password_asker)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/community_view.py", line 97, in change_account
    self.tab_history.change_account(account, self.password_asker)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 73, in change_account
    self.connect_progress()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/transactions_tab.py", line 119, in connect_progress
    self.app.current_account.loading_progressed.connect(progressing)
AttributeError: 'NoneType' object has no attribute 'loading_progressed'
```

**Comment by M5oul** [comment]
crash with password asker when sending money:
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/password_asker.py", line 39, in future_show
    future.set_result(pwd)
  File "/usr/lib64/python3.4/asyncio/futures.py", line 338, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <Future finished result=''>
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/password_asker.py", line 39, in future_show
    future.set_result(pwd)
  File "/usr/lib64/python3.4/asyncio/futures.py", line 338, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <Future finished result=''>
```

**Comment by Insoleet** [comment]
Should be fixed.

**Comment by M5oul** [comment]
Ok, I close all this issues which are fixed.
