### ISSUE TITLE
Cutecoin does not start due to network error

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#209]
Here is the trace:

    ERROR:__init__:Future/Task exception was never retrieved
    future: Task(<refresh>)<exception=NoPeerAvailable('', 0)>
    Traceback (most recent call last):
      File "/usr/lib/python3.4/asyncio/tasks.py", line 302, in _step
        result = next(coro)
      File "/home/gael/cutecoin/src/cutecoin/gui/community_tile.py", line 34, in refresh
      File "/home/gael/cutecoin/src/cutecoin/core/community.py", line 294, in members_pubkeys
      File "/home/gael/cutecoin/src/cutecoin/core/net/api/bma/access.py", line 174, in future_request
    cutecoin.tools.exceptions.NoPeerAvailable: Error : No peer answered in  community (0 peers available)

**Comment by c-geek** [comment]
This error occured on 0.11.
