### ISSUE TITLE
Add a parameter to adjust number of decimals for other referentials

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#216]
Actually, only UD referential have a parameter to adjust decimals numbers. It could be great to add this for other referentials.

**Comment by Insoleet** [comment]
The decimals are already applied to all referentials. But it makes no sense in the quantitative view because ther are only integers.

**Comment by M5oul** [comment]
I have a doubt about the fact that decimals are already applied to all referentials. Decimals makes sense in quantitative view with scientific display. For instance, 1.78987 TMB –> 1.78 TMB.
By the way, I can't open preference window, it crash:
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 194, in open_preferences_dialog
    dialog = PreferencesDialog(self.app)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/preferences.py", line 60, in __init__
    self.combox_proxytype.setCurrentText(self.app.preferences.get('proxy_type', "HTTP"))
AttributeError: 'PreferencesDialog' object has no attribute 'combox_proxytype'
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 194, in open_preferences_dialog
    dialog = PreferencesDialog(self.app)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/preferences.py", line 60, in __init__
    self.combox_proxytype.setCurrentText(self.app.preferences.get('proxy_type', "HTTP"))
AttributeError: 'PreferencesDialog' object has no attribute 'combox_proxytype'
```

**Comment by Insoleet** [comment]
Should be fixed !

**Comment by M5oul** [comment]
Thanks :dart:
