### ISSUE TITLE
Crash due to network connection fail

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#222]
Here the trace:

    DEBUG:__init__:debug:Client error : 95f6mEi2FWjbVCKx8VX44aqMjQQvcPe9bVj7EN9yaELZ
    DEBUG:__init__:debug:Exception handler executing
    ERROR:__init__:error:Future/Task exception was never retrieved
    future: Task(<get>)<exception=ClientOSError('Cannot connect to host metab.ucoin.io:64919 ssl:False',)>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 571, in _create_connection
        server_hostname=hinfo['hostname'] if sslcontext else None)
      File "/usr/lib/python3.4/asyncio/base_events.py", line 419, in create_connection
        raise exceptions[0]
      File "/usr/lib/python3.4/asyncio/base_events.py", line 410, in create_connection
        yield from self.sock_connect(sock, address)
      File "/usr/lib/python3.4/asyncio/futures.py", line 348, in __iter__
        yield self  # This tells Task to wait for completion.
      File "/usr/lib/python3.4/asyncio/tasks.py", line 351, in _wakeup
        value = future.result()
      File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
        raise self._exception
      File "/usr/lib/python3.4/asyncio/selector_events.py", line 300, in _sock_connect
        raise OSError(err, 'Connect call failed %s' % (address,))
    ConnectionRefusedError: [Errno 111] Connect call failed ('88.174.120.187', 64919)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 292, in connect
        transport, proto = yield from self._create_connection(req)
      File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 588, in _create_connection
        (req.host, req.port)) from exc
    aiohttp.errors.ClientOSError: Can not connect to metab.ucoin.io:64919

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/usr/lib/python3.4/asyncio/tasks.py", line 298, in _step
        result = coro.throw(exc)
      File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 474, in get
        ret = yield from request(hdrs.METH_GET, url, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 466, in request
        read_until_eof=read_until_eof)
      File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 131, in request
        conn = yield from self._connector.connect(req)
      File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 299, in connect
        'Cannot connect to host %s:%s ssl:%s' % key) from exc
    aiohttp.errors.ClientOSError: Cannot connect to host metab.ucoin.io:64919 ssl:False

**Comment by Insoleet** [comment]
I think you don't have the last release. I'll build you one tomorrow.
