### ISSUE TITLE
Crash after clean new installation

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#235]
Due to #234, I tried to remove my .config/cutecoin folder, started cutecoin and began adding a node. I used `Enter` key after putting `80` as port value (`twiced.fr` for host), and then I had below error:

```
ERROR:root:Future/Task exception was never retrieved
future: Task(<coroutine_check_register>)<exception=ValueError('Expecting value: line 1 column 1 (char 0)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
    result = coro.send(value)
  File "/home/gael/cutecoin/src/cutecoin/gui/process_cfg_community.py", line 90, in coroutine_check_register
  File "/home/gael/cutecoin/src/cutecoin/core/net/node.py", line 74, in from_address
  File "/usr/local/lib/python3.4/dist-packages/ucoinpy/api/bma/network/__init__.py", line 34, in __get__
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client_reqrep.py", line 715, in json
    return loads(self._content.decode(encoding))
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Insoleet** [comment]
Ok it seems that twiced.fr:80 redirects on your blog, thus no json data, thus a crash.
