### ISSUE TITLE
Crash when disconnecting from MB community

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#236]
```bash
DEBUG:node:jsonify:Saving node : HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk,metab.ucoin.io,88.174.120.187,9201,35053,meta_brouzouf,1,[]
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 75, in <lambda>
    self.homescreen.button_disconnect.clicked.connect(lambda :self.action_change_account(""))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 157, in action_change_account
    self.app.change_current_account(self.app.get_account(account_name))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/app.py", line 193, in change_current_account
    self.stop_current_account()
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/app.py", line 204, in stop_current_account
    self.save_cache(self.current_account)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/app.py", line 417, in save_cache
    json.dump(data, outfile, indent=4, sort_keys=True)
  File "/usr/lib64/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib64/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <TransferState.VALIDATED: 2> is not JSON serializable
```

**Comment by Insoleet** [comment]
This is an old bug which has been fixed since...

Are you sure your code is up to date with the git and your cache cleaned correctly ?

**Comment by M5oul** [comment]
I had a cleared cache and an update git.

**Comment by M5oul** [comment]
Seems fixed.
