### ISSUE TITLE
"Search identities" tab is loading forever or crash

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#243]
I'm using a beta build of 11.0.

When accessing to "Search identities" tab, I got this:

![image](https://cloud.githubusercontent.com/assets/969136/10868970/8e386252-809f-11e5-822a-5f4dda766abb.png)

Also, if I click on "Search > Members", Cutecoin crashes.

This is maybe linked to the new node I just added, which might not give the answers Cutecoin expects.

**Comment by Insoleet** [comment]
Any log available ?

**Comment by M5oul** [comment]
I have ever notice member search doesn't works on this tab. But, now, it won't display any member.
It's may be due to the new node. Some debug logs:
```bash
DEBUG:node:refresh_block:Requesting connection info: moul.re:8999
DEBUG:__init__:requests_get:Request : http://moul.re:8999/blockchain/current
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering
DEBUG:__init__:requests_get:Request : http://moul.re:8999/wot/lookup/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering/peers
DEBUG:__init__:requests_get:Request : http://moul.re:8999/node/summary
DEBUG:node:refresh_block:Client error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:node:refresh_informations:Client error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:node:refresh_uid:Client error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:node:refresh_peers:Client error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:node:refresh_summary:Client error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:node:refresh_block:Requesting connection info: 88.174.120.187:41610
DEBUG:__init__:requests_get:Request : http://88.174.120.187:41610/blockchain/current
DEBUG:__init__:requests_get:Request : http://88.174.120.187:41610/network/peering
DEBUG:__init__:requests_get:Request : http://88.174.120.187:41610/wot/lookup/AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:__init__:requests_get:Request : http://88.174.120.187:41610/network/peering/peers
DEBUG:__init__:requests_get:Request : http://88.174.120.187:41610/node/summary
DEBUG:node:refresh_block:Timeout error : AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:node:refresh_informations:Timeout error : AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:node:refresh_uid:Timeout error : AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:node:refresh_peers:Timeout error : AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:node:refresh_summary:Timeout error : AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:node:refresh_block:Requesting connection info: 88.174.120.187:31606
DEBUG:__init__:requests_get:Request : http://88.174.120.187:31606/blockchain/current
DEBUG:__init__:requests_get:Request : http://88.174.120.187:31606/network/peering
DEBUG:__init__:requests_get:Request : http://88.174.120.187:31606/wot/lookup/i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:__init__:requests_get:Request : http://88.174.120.187:31606/network/peering/peers
DEBUG:__init__:requests_get:Request : http://88.174.120.187:31606/node/summary
DEBUG:node:refresh_block:Timeout error : i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:node:refresh_informations:Timeout error : i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:node:refresh_uid:Timeout error : i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:node:refresh_peers:Timeout error : i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:node:refresh_summary:Timeout error : i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:node:refresh_block:Requesting connection info: 88.174.120.187:20301
DEBUG:__init__:requests_get:Request : http://88.174.120.187:20301/blockchain/current
DEBUG:__init__:requests_get:Request : http://88.174.120.187:20301/network/peering
DEBUG:__init__:requests_get:Request : http://88.174.120.187:20301/wot/lookup/AY3PVpZCEs3t6dTFr42xSya6ZbsAGirM1sdLkNKzsGX
DEBUG:__init__:requests_get:Request : http://88.174.120.187:20301/network/peering/peers
DEBUG:__init__:requests_get:Request : http://88.174.120.187:20301/node/summary
DEBUG:node:refresh_informations:{'status': 'UP', 'version': 1, 'signature': 'GpWx39gKd0yOuMYPS0G39xEk+waOIIPCfK5UOeVOejvSDs/8LakrRf44NqMo7xcideTmlu6UNmPd6oOlETJCBQ==', 'block': '39030-0000DFFA769D85E45A5F3F8DA31F4DD14411E84A', 'endpoints': ['BASIC_MERKLED_API 88.174.120.187 20301'], 'pubkey': 'AY3PVpZCEs3t6dTFr42xSya6ZbsAGirM1sdLkNKzsGX', 'currency': 'meta_brouzouf', 'raw': 'Version: 1\nType: Peer\nCurrency: meta_brouzouf\nPublicKey: AY3PVpZCEs3t6dTFr42xSya6ZbsAGirM1sdLkNKzsGX\nBlock: 39030-0000DFFA769D85E45A5F3F8DA31F4DD14411E84A\nEndpoints:\nBASIC_MERKLED_API 88.174.120.187 20301\n'}
DEBUG:node:refresh_block:Requesting connection info: metab.ucoin.io:9201
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/blockchain/current
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/wot/lookup/HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/network/peering/peers
DEBUG:__init__:requests_get:Request : http://metab.ucoin.io:9201/node/summary
DEBUG:node:refresh_informations:{'status': 'UP', 'version': 1, 'signature': 'B/IaWGvF38r3GfMNNvWjv+To5WHMLZ5eWfrNwRPioYi2MGlmHhTj/4PMvU+IiLbzEyp7ySw9xCwp8wgHs/LKBw==', 'block': '39038-0000FAF2C3E10D8E21C5BEB515A8DD37D3325DD6', 'endpoints': ['BASIC_MERKLED_API metab.ucoin.io 88.174.120.187 9201'], 'pubkey': 'HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk', 'currency': 'meta_brouzouf', 'raw': 'Version: 1\nType: Peer\nCurrency: meta_brouzouf\nPublicKey: HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk\nBlock: 39038-0000FAF2C3E10D8E21C5BEB515A8DD37D3325DD6\nEndpoints:\nBASIC_MERKLED_API metab.ucoin.io 88.174.120.187 9201\n'}
DEBUG:node:refresh_block:Requesting connection info: moul.re:8999
DEBUG:__init__:requests_get:Request : http://moul.re:8999/blockchain/current
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering
DEBUG:__init__:requests_get:Request : http://moul.re:8999/wot/lookup/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering/peers
DEBUG:__init__:requests_get:Request : http://moul.re:8999/node/summary
DEBUG:node:refresh_block:Client error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:node:refresh_informations:Client error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:node:refresh_uid:Client error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:node:refresh_summary:Client error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:node:refresh_peers:Client error : J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:node:refresh_block:Requesting connection info: 88.174.120.187:41610
DEBUG:__init__:requests_get:Request : http://88.174.120.187:41610/blockchain/current
DEBUG:__init__:requests_get:Request : http://88.174.120.187:41610/network/peering
DEBUG:__init__:requests_get:Request : http://88.174.120.187:41610/wot/lookup/AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:__init__:requests_get:Request : http://88.174.120.187:41610/network/peering/peers
DEBUG:__init__:requests_get:Request : http://88.174.120.187:41610/node/summary
DEBUG:node:refresh_block:Timeout error : AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:node:refresh_informations:Timeout error : AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:node:refresh_uid:Timeout error : AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:node:refresh_peers:Timeout error : AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:node:refresh_summary:Timeout error : AoNDTA23TMtp76jV4NTuE6aM6X4mxsSqYBAAKBJtYcYj
DEBUG:node:refresh_block:Requesting connection info: 88.174.120.187:31606
DEBUG:__init__:requests_get:Request : http://88.174.120.187:31606/blockchain/current
DEBUG:__init__:requests_get:Request : http://88.174.120.187:31606/network/peering
DEBUG:__init__:requests_get:Request : http://88.174.120.187:31606/wot/lookup/i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:__init__:requests_get:Request : http://88.174.120.187:31606/network/peering/peers
DEBUG:__init__:requests_get:Request : http://88.174.120.187:31606/node/summary
DEBUG:node:refresh_block:Timeout error : i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:node:refresh_informations:Timeout error : i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:node:refresh_uid:Timeout error : i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:node:refresh_peers:Timeout error : i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:node:refresh_summary:Timeout error : i2P6aUTQVmb3mC9YH7GeFuHZcVSMzDb8d8WvmySJs33
DEBUG:node:refresh_block:Requesting connection info: 88.174.120.187:20301
DEBUG:__init__:requests_get:Request : http://88.174.120.187:20301/blockchain/current
DEBUG:__init__:requests_get:Request : http://88.174.120.187:20301/network/peering
DEBUG:__init__:requests_get:Request : http://88.174.120.187:20301/wot/lookup/AY3PVpZCEs3t6dTFr42xSya6ZbsAGirM1sdLkNKzsGX
DEBUG:__init__:requests_get:Request : http://88.174.120.187:20301/network/peering/peers
DEBUG:__init__:requests_get:Request : http://88.174.120.187:20301/node/summary
```

**Comment by Insoleet** [comment]
Yes I'm looking into this. Maybe a mix between the really slow network and aiohttp bugs. To be continued...

**Comment by c-geek** [comment]
For the crash:
```
ERROR:__init__:error:Future/Task exception was never retrieved
future: Task(<refresh_identities>)<exception=UnboundLocalError("local variable 'membership_data' referenced before assignment",)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
    result = coro.send(value)
  File "/home/gael/cutecoin/src/cutecoin/gui/identities_tab.py", line 253, in refresh_identities
  File "/home/gael/cutecoin/src/cutecoin/models/identities.py", line 136, in refresh_identities
  File "/home/gael/cutecoin/src/cutecoin/models/identities.py", line 115, in identity_data
  File "/home/gael/cutecoin/src/cutecoin/core/registry/identity.py", line 147, in get_expiration_date
  File "/home/gael/cutecoin/src/cutecoin/core/registry/identity.py", line 187, in membership
UnboundLocalError: local variable 'membership_data' referenced before assignment
```

**Comment by Insoleet** [comment]
It's a bug with the new node : 
http://88.174.120.187:20301/blockchain/memberships/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
