### ISSUE TITLE
Cannot renew membership

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#250]
```
Task exception was never retrieved
future: <Task finished coro=<send_membership_demand() done, defined at /home/gael/cutecoin/src/cutecoin/gui/community_view.py:297> exception=KeyError(<class 'ucoinpy.api.bma.blockchain.Membership'>,)>
Traceback (most recent call last):
  File "/home/gael/.pyenv/versions/3.4.3/lib/python3.4/asyncio/tasks.py", line 238, in _step
  File "/home/gael/cutecoin/src/cutecoin/gui/community_view.py", line 303, in send_membership_demand
  File "/home/gael/cutecoin/src/cutecoin/core/account.py", line 455, in send_membership
  File "/home/gael/cutecoin/src/cutecoin/core/net/api/bma/access.py", line 308, in broadcast
  File "/home/gael/cutecoin/src/cutecoin/core/net/api/bma/access.py", line 183, in _invalidate_cache
KeyError: <class 'ucoinpy.api.bma.blockchain.Membership'>
```

**Comment by Insoleet** [comment]
It's a bug in your release that was fixed yesterday. 6e0d1b8abac322cf04f25a2547ec8df557763e0a

Sorry for the inconvenience !

**Comment by c-geek** [comment]
Yes but .. I got the build of yesterday, precisely. Shouldn't I have the fix in my version?

**Comment by Insoleet** [comment]
I think it was one last commit after building your version... ^^ I checked, it's working nicely. I'll give you one build at the FMM6 !
