### ISSUE TITLE
Crash with memberships url containg blockNumber as a string

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#251]
I *suppose* it is during network refresh.
```
Task exception was never retrieved
future: <Task finished coro=<refresh_block() done, defined at /home/gael/cutecoin/src/cutecoin/gui/community_view.py:142> exception=TypeError('unorderable types: str() > int()',)>
Traceback (most recent call last):
  File "/home/gael/.pyenv/versions/3.4.3/lib/python3.4/asyncio/tasks.py", line 238, in _step
  File "/home/gael/cutecoin/src/cutecoin/gui/community_view.py", line 154, in refresh_block
  File "/home/gael/cutecoin/src/cutecoin/core/registry/identity.py", line 415, in membership_expiration_time
  File "/home/gael/cutecoin/src/cutecoin/core/registry/identity.py", line 182, in membership
TypeError: unorderable types: str() > int()
```

**Comment by Insoleet** [comment]
It happened on the following line : 

```python
            for ms in search['memberships']:
                if ms['blockNumber'] > block_number:
```

It looks like it's due to a node answering the block number as a string.. Weird, I can't reproduce it on any url.
I really need to do some json data validation for next version.

**Comment by Insoleet** [comment]
So this happens again despite data validation.

@c-geek , in the logs with "-d", what is the membership url requested before the crash ? Just look for a log with for a line with "request : [url]" some time before the exception...

**Comment by c-geek** [comment]
I'm under Windows, I do not see it.

**Comment by c-geek** [comment]
Oh yes I can using "cutecoin.exe -d":

```
Refresh 8 identities
Request : http://metab.ucoin.io:9201/blockchain/memberships/EKSwGczvCGi5rFKRQYEaq3ncDmkdL7ukzt4dFrieDom
Request : http://metab.ucoin.io:9201/blockchain/block/466
Request : http://metab.ucoin.io:9201/wot/certifiers-of/EKSwGczvCGi5rFKRQYEaq3ncDmkdL7ukzt4dFrieDom
Request : http://metab.ucoin.io:9201/blockchain/block/40888
Request : http://metab.ucoin.io:9201/blockchain/block/471
Request : http://metab.ucoin.io:9201/wot/certifiers-of/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
Request : http://metab.ucoin.io:9201/blockchain/memberships/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
Request : http://metab.ucoin.io:9201/wot/certifiers-of/5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of
Request : http://metab.ucoin.io:9201/wot/certifiers-of/2sq8bBDQGK74f1eD3mAPQVgHCmFdijZr9nbv16FwbokX
Request : http://metab.ucoin.io:9201/blockchain/block/24674
Request : http://metab.ucoin.io:9201/blockchain/block/489
Request : http://metab.ucoin.io:9201/wot/certifiers-of/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU
Request : http://metab.ucoin.io:9201/blockchain/block/40783
Request : http://metab.ucoin.io:9201/blockchain/block/579
Request : http://metab.ucoin.io:9201/wot/certifiers-of/ATkjQPa4sn4LBF69jqEPzFtRdHYJs6MJQjvP8JdN7MtN
Request : http://metab.ucoin.io:9201/blockchain/memberships/2sq8bBDQGK74f1eD3mAPQVgHCmFdijZr9nbv16FwbokX
Request : http://metab.ucoin.io:9201/wot/certifiers-of/FLgGeBDezXHdiCSqmS6LYu7nwMkPmx5oDTgmCBLMsEL6
Request : http://metab.ucoin.io:9201/blockchain/block/764
Request : http://metab.ucoin.io:9201/wot/lookup/FLgGeBDezXHdiCSqmS6LYu7nwMkPmx5oDTgmCBLMsEL6
Exception handler executing
Task exception was never retrieved
future: <Task finished coro=<_async_search_direct_connections() done, defined at C:\projects\cutecoin\src\cutecoin\gui\identities_tab.py:218> exception=TypeError('unorderable types: str() > int()',)>
Traceback (most recent call last):
  File "C:\Python34_64\envs\test-environment\lib\asyncio\tasks.py", line 238, in _step
  File "C:\projects\cutecoin\src\cutecoin\gui\identities_tab.py", line 242, in _async_search_direct_connections
  File "C:\projects\cutecoin\src\cutecoin\gui\identities_tab.py", line 252, in refresh_identities
  File "C:\projects\cutecoin\src\cutecoin\models\identities.py", line 145, in refresh_identities
  File "C:\projects\cutecoin\src\cutecoin\models\identities.py", line 124, in identity_data
  File "C:\projects\cutecoin\src\cutecoin\core\registry\identity.py", line 147, in get_expiration_date
  File "C:\projects\cutecoin\src\cutecoin\core\registry\identity.py", line 182, in membership
TypeError: unorderable types: str() > int()
```

**Comment by Insoleet** [comment]
Ok it seems like you don't have data validation in your build.

Using a unit test, I reproduce your error with the result of the URL  http://metab.ucoin.io/blockchain/memberships/2sq8bBDQGK74f1eD3mAPQVgHCmFdijZr9nbv16FwbokX

The third element is the following 
```json
    {
      "version": "1",
      "currency": "test_currency",
      "membership": "IN",
      "blockNumber": "40806",
      "blockHash": "0000B1ED8B41DAE25E270DC802B1829A45299DEF"
    },
```

Here we can find that the blockNumber is a string, it's an error.

**Comment by c-geek** [comment]
OK. Is there any working build of 0.11 for Windows I can use?

**Comment by Insoleet** [comment]
The appveyor build is failing to upload the generated artifacts... Maybe you can just follow the windows build procedure. Since it is using Conda, it should be easy to do. ( https://github.com/ucoin-io/cutecoin/wiki/Cutecoin-install-for-developpers )
