### ISSUE TITLE
Exception not caught

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#256]
```
Task exception was never retrieved
future: <Task finished coro=<_async_search_direct_connections() done, defined at C:\projects\cutecoin\src\cutecoin\gui\identities_tab.py:218> exception=TypeError('unorderable types: str() > int()',)>
Traceback (most recent call last):
  File "C:\Python34_64\envs\test-environment\lib\asyncio\tasks.py", line 238, in _step
  File "C:\projects\cutecoin\src\cutecoin\gui\identities_tab.py", line 242, in _async_search_direct_connections
  File "C:\projects\cutecoin\src\cutecoin\gui\identities_tab.py", line 252, in refresh_identities
  File "C:\projects\cutecoin\src\cutecoin\models\identities.py", line 145, in refresh_identities
  File "C:\projects\cutecoin\src\cutecoin\models\identities.py", line 124, in identity_data
  File "C:\projects\cutecoin\src\cutecoin\core\registry\identity.py", line 147, in get_expiration_date
  File "C:\projects\cutecoin\src\cutecoin\core\registry\identity.py", line 182, in membership
TypeError: unorderable types: str() > int()
```

**Comment by c-geek** [comment]
The bug is stucking me, once cutecoin is launched with my account (cgeek) the exception occurs few seconds later. No matter what I'm doing.

I've deleted my cache, deleted my cutecoin folder + added my account again, still occuring.

**Comment by Insoleet** [comment]
Same bug as https://github.com/ucoin-io/cutecoin/issues/251
