### ISSUE TITLE
Crash after sending a transaction

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#258]
When I send a TX cutecoin crashes. The TX seems to be received by the node however.

This is the 0.11 version made during FMM6.

```
DEBUG:wallet:send_money:TX : Version: 1
Type: Transaction
Currency: meta_brouzouf
Issuers:
HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk
Inputs:
0:D:40716:0010E466C5E8733E1985B11C24455AAF170C3359:245849316780950
Outputs:
8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU:123140153659379
HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk:122709163121571
Comment: CAF

DEBUG:document:sign:Signature : 
WvfejYN5PnlLp1kYdYg0vkwegKTpYpHtk3PC2wKsNNaJta+6tlYCUvwJhlpcGN+ks6l1qzkQWl95Nm4XJ7WQCA==
DEBUG:wallet:send_money:Transaction : Version: 1
Type: Transaction
Currency: meta_brouzouf
Issuers:
HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk
Inputs:
0:D:40716:0010E466C5E8733E1985B11C24455AAF170C3359:245849316780950
Outputs:
8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU:123140153659379
HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk:122709163121571
Comment: CAF
WvfejYN5PnlLp1kYdYg0vkwegKTpYpHtk3PC2wKsNNaJta+6tlYCUvwJhlpcGN+ks6l1qzkQWl95Nm4XJ7WQCA==

DEBUG:access:broadcast:Trying to connect to : HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk
DEBUG:__init__:post:do some work with
DEBUG:__init__:post:and send back
DEBUG:__init__:requests_post:POST : {'transaction': 'Version: 1\nType: Transaction\nCurrency: meta_brouzouf\nIssuers:\nHnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk\nInputs:\n0:D:40716:0010E466C5E8733E1985B11C24455AAF170C3359:245849316780950\nOutputs:\n8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU:123140153659379\nHnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk:122709163121571\nComment: CAF\nWvfejYN5PnlLp1kYdYg0vkwegKTpYpHtk3PC2wKsNNaJta+6tlYCUvwJhlpcGN+ks6l1qzkQWl95Nm4XJ7WQCA==\n'}
DEBUG:access:broadcast:Trying to connect to : CnRzLoh8BgBvjDSUFmqNXtxtf2SBoNb6jkzw3dw2r4Sh
DEBUG:__init__:post:do some work with
DEBUG:__init__:post:and send back
DEBUG:__init__:requests_post:POST : {'transaction': 'Version: 1\nType: Transaction\nCurrency: meta_brouzouf\nIssuers:\nHnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk\nInputs:\n0:D:40716:0010E466C5E8733E1985B11C24455AAF170C3359:245849316780950\nOutputs:\n8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU:123140153659379\nHnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk:122709163121571\nComment: CAF\nWvfejYN5PnlLp1kYdYg0vkwegKTpYpHtk3PC2wKsNNaJta+6tlYCUvwJhlpcGN+ks6l1qzkQWl95Nm4XJ7WQCA==\n'}
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<accept() done, defined at /home/gael/cutecoin/src/cutecoin/gui/transfer.py:93> exception=TypeError("argument of type 'Block' is not iterable",)>
Traceback (most recent call last):
  File "/home/gael/.pyenv/versions/3.4.3/lib/python3.4/asyncio/tasks.py", line 238, in _step
  File "/home/gael/cutecoin/src/cutecoin/gui/transfer.py", line 118, in accept
  File "/home/gael/cutecoin/src/cutecoin/core/wallet.py", line 281, in send_money
  File "/home/gael/cutecoin/src/cutecoin/core/transfer.py", line 355, in send
  File "/home/gael/cutecoin/src/cutecoin/core/transfer.py", line 319, in run_state_transitions
  File "/home/gael/cutecoin/src/cutecoin/core/transfer.py", line 300, in _try_transition
  File "/home/gael/cutecoin/src/cutecoin/core/transfer.py", line 76, in <lambda>
  File "/home/gael/cutecoin/src/cutecoin/core/transfer.py", line 205, in _broadcast_failure
TypeError: argument of type 'Block' is not iterable
```

**Comment by M5oul** [comment]
I could reproduce it.
