### ISSUE TITLE
Cannot start cutecoin

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#261]
```
Traceback (most recent call last):
  File "/home/gael/.pyenv/versions/3.4.3/lib/python3.4/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "src/cutecoin/main.py", line 59, in <module>
  File "/home/gael/cutecoin/src/cutecoin/core/app.py", line 95, in startup
  File "/home/gael/cutecoin/src/cutecoin/core/app.py", line 142, in get_account
  File "/home/gael/cutecoin/src/cutecoin/core/app.py", line 252, in load_account
  File "/home/gael/cutecoin/src/cutecoin/core/app.py", line 289, in load_cache
  File "/home/gael/.pyenv/versions/3.4.3/lib/python3.4/json/__init__.py", line 268, in load
  File "/home/gael/.pyenv/versions/3.4.3/lib/python3.4/json/__init__.py", line 318, in loads
  File "/home/gael/.pyenv/versions/3.4.3/lib/python3.4/json/decoder.py", line 343, in decode
  File "/home/gael/.pyenv/versions/3.4.3/lib/python3.4/json/decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 8285 column 46 (char 509387)
```

**Comment by c-geek** [comment]
Also, I do not find any `~/.config/cutecoin` folder. That's weird.

**Comment by Insoleet** [comment]
This error occurs when the software crashes during saving data.

The fact that you cannot find the cutecoin directory is really weird thought.  What does "echo $XDG_CONFIG_HOME" prints in your console ?

**Comment by c-geek** [comment]
Empty string.

**Comment by Insoleet** [comment]
So the folder should be present in $HOME/.config ...

**Comment by c-geek** [comment]
Ahem sorry ... the cutecoin folder is indeed here. It was hidden behind another window of my second screen >_<.
