### ISSUE TITLE
Crash on WoT tab

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#274]
When I tried to certify inso indentity from wot tab, cutecoin crashed:
```bash
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering/peers
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<sign_node() done, defined at /home/moul/projects/cutecoin/build/src/cutecoin/gui/wot_tab.py:312> exception=TypeError("from_handled_data() missing 1 required positional argument: 'community'",)>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/moul/projects/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 319, in sign_node
    self.community
TypeError: from_handled_data() missing 1 required positional argument: 'community'
```

**Comment by M5oul** [comment]
And:
When I search `jaun` in the search field of the WoT tab, cutecoin crash:
```bash
  File "/home/moul/projects/cutecoin/build/src/cutecoin/gui/wot_tab.py", line 298, in select_node
    self.community
TypeError: from_handled_data() missing 1 required positional argument: 'community'
```
