### ISSUE TITLE
Crash whith bad port

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/cutecoin#61]
>
./cutecoin/exe.linux-x86_64-3.4/cutecoin 
Traceback (most recent call last):
  File "/home/inso/cutecoin/src/cutecoin/gui/currency_tab.py", line 182, in refresh_block
TypeError: unorderable types: QDateTime() > int()
bash-4.3$ ./cutecoin/exe.linux-x86_64-3.4/cutecoin 
Traceback (most recent call last):
  File "/home/inso/cutecoin/src/cutecoin/gui/currency_tab.py", line 182, in refresh_block
TypeError: unorderable types: QDateTime() > int()
Traceback (most recent call last):
  File "/home/inso/cutecoin/src/cutecoin/gui/process_cfg_community.py", line 175, in add_node
TypeError: 'Peering' object is not subscriptable
Traceback (most recent call last):
  File "/home/inso/cutecoin/src/cutecoin/gui/process_cfg_community.py", line 175, in add_node
TypeError: 'Peering' object is not subscriptable
Processus arrêté

**Comment by M5oul** [comment]
CuteCoin crashed joinning metab.ucoin.io on 7201, 7210 or 8210 port, I can not remember, I can not reproduce the bug.

**Comment by Insoleet** [comment]
Fixed https://github.com/ucoin-io/cutecoin/commit/6a9e89b0cb0c0a05a42c5896d69d0ad9e985bcd5
