### ISSUE TITLE
Exceptions not catched in 0.8.0...

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#70]
First one  appears repeatedly as a serie...
```
Traceback (most recent call last):
  File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/models/txhistory.py", line 54, in lessThan
    return (left_data < right_data)
TypeError: unorderable types: str() < int()
```
This one appears once in a while...
```
Traceback (most recent call last):
  File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/gui/currency_tab.py", line 182, in refresh_block
    will_expire_soon = (current_time > expiration_date*1000 - warning_expiration_time*1000)
TypeError: unorderable types: QDateTime() > int()
```

Don't have much infos for now. To be continued...

**Comment by vtexier** [comment]
First exception not seen again...
Second exception fixed in c1b05990e8215c849caab637f0e0a7e9c81698b1
