### ISSUE TITLE
Account loading stuck for currencies with no UD yet written

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#93]
I'm with a local testing currency which does not have UD written yet. On "Accuont > Open" click, cutecoin get stuck with following logs:

```
DEBUG:connectionpool:"GET /blockchain/with/ud HTTP/1.1" 200 38
Traceback (most recent call last):
  File "/home/inso/cutecoin/src/cutecoin/gui/mainwindow.py", line 105, in loader_finished
  File "/home/inso/cutecoin/src/cutecoin/gui/mainwindow.py", line 291, in refresh
  File "/home/inso/cutecoin/src/cutecoin/gui/mainwindow.py", line 214, in refresh_communities
  File "/home/inso/cutecoin/src/cutecoin/gui/currency_tab.py", line 155, in refresh
  File "/home/inso/cutecoin/src/cutecoin/gui/informations_tab.py", line 28, in __init__
  File "/home/inso/cutecoin/src/cutecoin/gui/informations_tab.py", line 62, in refresh
TypeError: 'bool' object is not subscriptable
```

I know it might be pretty occasional to have currencies without monetary mass, but in a first time it exists. It would be nice if cutecoin could handle this case!

edit: BTW, I don't really understand why I ge `/home/inso` in my logs

**Comment by vtexier** [comment]
Fixed in 7864c117ed6d64f2ec81364885cc30a7f507e5f1
