### ISSUE TITLE
Exceptions not catched in 0.9.0...

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#96]
>
    Traceback (most recent call last):
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/models/network.py", line 31, in lessThan
        left_data = self.sourceModel().data(left, Qt.DisplayRole)
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/models/network.py", line 125, in data
        return self.data_node(node)[col]
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/models/network.py", line 103, in data_node
        is_member = node.pubkey in self.community.members_pubkeys()
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/community.py", line 362, in members_pubkeys
        memberships = self.request(bma.wot.Members)
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/community.py", line 381, in request
        return self._cache.request(request, req_args, get_args)
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/community.py", line 87, in request
        cached=False)
      File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/community.py", line 404, in request
        raise NoPeerAvailable(self.currency, len(nodes))
    cutecoin.tools.exceptions.NoPeerAvailable: Error : No peer answered in meta_brouzouf community (0 peers available)

**Comment by vtexier** [comment]
Fixed in 44af6354c08d0f585cb8b5297f84a69e34562e84
